require("adimitri.plugins-setup")
require("adimitri.core.options")
require("adimitri.core.keymaps")
require("adimitri.core.colorscheme")
require("adimitri.plugins.nvim-tree")
require("adimitri.plugins.gitsigns")
