require("adimitri.plugins-setup")
require("adimitri.core.options")
require("adimitri.core.keymaps")
require("adimitri.core.colorscheme")
require("adimitri.plugins.neo-tree")
require("adimitri.plugins.gitsigns")
